"""create skills table

Revision ID: e62685f9cd20
Revises: 70f00c79670f
Create Date: 2026-03-08 10:49:05.998750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e62685f9cd20'
down_revision: Union[str, Sequence[str], None] = '70f00c79670f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('duolingo_level_id', sa.String(length=100), nullable=False),
    sa.Column('duolingo_skill_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('subtype', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('finished_sessions', sa.Integer(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('absolute_node_index', sa.Integer(), nullable=True),
    sa.Column('position_index', sa.Integer(), nullable=False),
    sa.Column('section_index', sa.Integer(), nullable=False),
    sa.Column('unit_index', sa.Integer(), nullable=True),
    sa.Column('lesson_number', sa.Integer(), nullable=True),
    sa.Column('crown_level_index', sa.Integer(), nullable=True),
    sa.Column('cefr_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_duolingo_level_id'), 'skills', ['duolingo_level_id'], unique=False)
    op.create_index(op.f('ix_skills_language_id'), 'skills', ['language_id'], unique=False)
    op.create_index(op.f('ix_skills_position_index'), 'skills', ['position_index'], unique=False)
    op.create_index(op.f('ix_skills_user_id'), 'skills', ['user_id'], unique=False)
    op.drop_column('languages', 'updated_at')
    op.drop_column('languages', 'created_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('languages', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('languages', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_skills_user_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_position_index'), table_name='skills')
    op.drop_index(op.f('ix_skills_language_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_duolingo_level_id'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
