export { formBlocks } from './blockFormation'
export { groupCompoundsIntoBlocks } from './blockGrouping'
export { placeBlocks } from './blockPlacement'
export type { Block } from './blockFormation'
export type { BlockFootprint, BlockPlacementResult } from './blockPlacement'
